import { parseTypeScriptFile } from '../zod-generator/type-parser'
import {
  buildStoreString,
  generateImports,
  type StoreBuilderOptions,
  type StoreBuilderContext,
} from './store-builder'
import * as path from 'path'

export interface GeneratorOptions {
  verbose?: boolean
  persist?: boolean
  storageKey?: string
}

export interface GeneratorResult {
  code: string
  warnings: string[]
  generatedStores: string[]
}

export async function generateZustandStore(
  inputPath: string,
  options: GeneratorOptions = {}
): Promise<GeneratorResult> {
  const { verbose = false, persist = true, storageKey } = options
  const warnings: string[] = []
  const generatedStores: string[] = []

  if (verbose) {
    console.log(`Parsing: ${inputPath}`)
  }

  // Parse the TypeScript file
  const { declarations } = parseTypeScriptFile(inputPath)

  if (verbose) {
    console.log(`Found ${declarations.length} type declarations`)
  }

  // Build context
  const context: StoreBuilderContext = {
    warnings,
  }

  const builderOptions: StoreBuilderOptions = {
    persist,
    storageKey,
  }

  // Generate stores
  const storeStrings: string[] = []

  for (const decl of declarations) {
    if (!decl.isExported) {
      if (verbose) {
        console.log(`Skipping non-exported type: ${decl.name}`)
      }
      continue
    }

    const storeString = buildStoreString(decl, builderOptions, context)
    if (storeString) {
      storeStrings.push(storeString)
      generatedStores.push(`use${decl.name}Store`)

      if (verbose) {
        console.log(`Generated: use${decl.name}Store`)
      }
    }
  }

  // Build the final output
  const relativePath = path.basename(inputPath)
  const header = [
    '// Auto-generated by generate-store - DO NOT EDIT',
    `// Source: ${relativePath}`,
    '',
    generateImports(builderOptions),
    '',
  ].join('\n')

  const code = [header, ...storeStrings, ''].join('\n')

  return {
    code,
    warnings: context.warnings,
    generatedStores,
  }
}

export { buildStoreString, generateImports } from './store-builder'
export type { StoreBuilderOptions, StoreBuilderContext } from './store-builder'
