import { parseTypeScriptFile } from '../zod-generator/type-parser'
import {
  buildFormComponent,
  type FormBuilderOptions,
  type FormBuilderContext,
  type FormBuildResult,
} from './form-builder'
import * as path from 'path'

export interface GeneratorOptions {
  verbose?: boolean
  schemaImportPath?: string
  storeImportPath?: string
}

export interface GeneratorResult {
  code: string
  warnings: string[]
  generatedForms: string[]
}

export async function generateForm(
  inputPath: string,
  options: GeneratorOptions = {}
): Promise<GeneratorResult> {
  const {
    verbose = false,
    schemaImportPath = '../schemas',
    storeImportPath = '../stores/generated',
  } = options

  const warnings: string[] = []
  const generatedForms: string[] = []

  if (verbose) {
    console.log(`Parsing: ${inputPath}`)
  }

  // Parse the TypeScript file
  const { declarations } = parseTypeScriptFile(inputPath)

  if (verbose) {
    console.log(`Found ${declarations.length} type declarations`)
  }

  // Build context
  const context: FormBuilderContext = {
    warnings,
  }

  // Get the base name for import paths
  const inputBasename = path.basename(inputPath).replace(/\.tsx?$/, '')

  const builderOptions: FormBuilderOptions = {
    schemaImportPath: `${schemaImportPath}/${inputBasename}.schema`,
    storeImportPath: `${storeImportPath}/${inputBasename}.store`,
  }

  // Generate forms and collect imports
  const formResults: FormBuildResult[] = []

  for (const decl of declarations) {
    if (!decl.isExported) {
      if (verbose) {
        console.log(`Skipping non-exported type: ${decl.name}`)
      }
      continue
    }

    const result = buildFormComponent(decl, builderOptions, context)
    if (result) {
      formResults.push(result)
      generatedForms.push(`${decl.name}Form`)

      if (verbose) {
        console.log(`Generated: ${decl.name}Form`)
      }
    }
  }

  // Build consolidated imports
  const schemaImports = formResults.map((r) => r.schemaName)
  const storeImports = formResults.map((r) => r.storeName)

  const relativePath = path.basename(inputPath)
  const imports = [
    '// Auto-generated by generate-form - DO NOT EDIT',
    `// Source: ${relativePath}`,
    '// @ts-nocheck',
    '',
    "import { useState, useCallback } from 'react'",
    "import { z } from 'zod'",
    "import Box from '@mui/material/Box'",
    "import Card from '@mui/material/Card'",
    "import TextField from '@mui/material/TextField'",
    "import Button from '@mui/material/Button'",
    "import IconButton from '@mui/material/IconButton'",
    "import FormControl from '@mui/material/FormControl'",
    "import FormControlLabel from '@mui/material/FormControlLabel'",
    "import FormHelperText from '@mui/material/FormHelperText'",
    "import InputLabel from '@mui/material/InputLabel'",
    "import Select from '@mui/material/Select'",
    "import MenuItem from '@mui/material/MenuItem'",
    "import Switch from '@mui/material/Switch'",
    "import CircularProgress from '@mui/material/CircularProgress'",
    "import Alert from '@mui/material/Alert'",
    "import Stack from '@mui/material/Stack'",
    "import Typography from '@mui/material/Typography'",
    "import DeleteIcon from '@mui/icons-material/Delete'",
    "import AddIcon from '@mui/icons-material/Add'",
    `import { ${schemaImports.join(', ')} } from '${builderOptions.schemaImportPath}'`,
    `import { ${storeImports.join(', ')} } from '${builderOptions.storeImportPath}'`,
  ].join('\n')

  // Combine components
  const components = formResults.map((r) => r.component).join('\n\n')

  const code = [imports, '', components, ''].join('\n')

  return {
    code,
    warnings: context.warnings,
    generatedForms,
  }
}

export { buildFormComponent } from './form-builder'
export type { FormBuilderOptions, FormBuilderContext } from './form-builder'
