// Auto-generated by generate-zod - DO NOT EDIT
// Source: example.ts

import { z } from 'zod';

export const AirPlaneSchema = z.object({
  id: z.string(),
  model: z.string(),
  manufacturer: z.string(),
  capacity: z.number(),
  range: z.number(),
  inService: z.boolean(),
});

// Type exports
export type AirPlane = z.infer<typeof AirPlaneSchema>;
