// Auto-generated by generate-zod - DO NOT EDIT
// Source: otherExample.ts

import { z } from 'zod';

export const UserSchema = z.object({
  id: z.string(),
  name: z.string(),
  email: z.string(),
  isActive: z.boolean(),
  age: z.number(),
  addresses: z.array(z.object({
  street: z.string(),
  city: z.string(),
  state: z.string(),
  zipCode: z.string(),
  country: z.string(),
  isDefault: z.boolean(),
})),
  orders: z.array(z.object({
  orderId: z.string(),
  status: z.enum(["pending", "processing", "shipped", "delivered", "cancelled"]),
  priority: z.enum(["low", "medium", "high"]),
  totalAmount: z.number(),
  itemCount: z.number(),
  product: z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  price: z.number(),
  inStock: z.boolean(),
  quantity: z.number(),
}),
})),
});

// Type exports
export type User = z.infer<typeof UserSchema>;
