// Auto-generated by generate-zod - DO NOT EDIT
// Source: showcase.ts

import { z } from 'zod';

export const ShowcaseAddressSchema = z.object({
  label: z.string(),
  street: z.string(),
  city: z.string(),
  state: z.string(),
  zipCode: z.string(),
  country: z.string(),
  isDefault: z.boolean(),
});
export const ShowcaseManagerSchema = z.object({
  name: z.string(),
  email: z.string(),
  phone: z.string(),
});
export const ShowcaseExperienceSchema = z.object({
  company: z.string(),
  position: z.string(),
  isCurrent: z.boolean(),
  employmentType: z.enum(["full-time", "part-time", "contract", "internship"]),
  salary: z.number(),
});
export const ShowcaseNotificationSchema = z.object({
  channel: z.enum(["email", "sms", "push", "slack"]),
  frequency: z.enum(["instant", "daily", "weekly", "monthly"]),
  enabled: z.boolean(),
});
export const ShowcaseSocialLinkSchema = z.object({
  platform: z.enum(["twitter", "linkedin", "github", "facebook", "instagram"]),
  url: z.string(),
  isPublic: z.boolean(),
});
export const MUIShowcaseSchema = z.object({
  firstName: z.string(),
  lastName: z.string(),
  email: z.string(),
  website: z.string(),
  age: z.number(),
  salary: z.number(),
  yearsOfExperience: z.number(),
  isActive: z.boolean(),
  receiveNewsletter: z.boolean(),
  agreeToTerms: z.boolean(),
  darkMode: z.boolean(),
  birthDate: z.date(),
  hireDate: z.date(),
  status: z.enum(["active", "inactive", "pending", "suspended"]),
  priority: z.enum(["low", "medium", "high", "critical"]),
  role: z.enum(["admin", "editor", "viewer", "guest"]),
  department: z.enum(["engineering", "design", "marketing", "sales", "hr", "finance"]),
  skills: z.array(z.string()),
  phoneNumbers: z.array(z.string()),
  addresses: z.array(ShowcaseAddressSchema),
  experiences: z.array(ShowcaseExperienceSchema),
  notifications: z.array(ShowcaseNotificationSchema),
  socialLinks: z.array(ShowcaseSocialLinkSchema),
});

// Type exports
export type ShowcaseAddress = z.infer<typeof ShowcaseAddressSchema>;
export type ShowcaseManager = z.infer<typeof ShowcaseManagerSchema>;
export type ShowcaseExperience = z.infer<typeof ShowcaseExperienceSchema>;
export type ShowcaseNotification = z.infer<typeof ShowcaseNotificationSchema>;
export type ShowcaseSocialLink = z.infer<typeof ShowcaseSocialLinkSchema>;
export type MUIShowcase = z.infer<typeof MUIShowcaseSchema>;
