// Auto-generated by generate-zod - DO NOT EDIT
// Source: themeStore.ts

import { z } from 'zod';

export const ThemeConfigSchema = z.object({
  primary: z.string(),
  secondary: z.string(),
  error: z.string(),
  warning: z.string(),
  info: z.string(),
  success: z.string(),
  background: z.string(),
  paper: z.string(),
  text: z.string(),
  fontFamily: z.string(),
  borderRadius: z.number(),
  mode: z.enum(["light", "dark"]),
});

// Type exports
export type ThemeConfig = z.infer<typeof ThemeConfigSchema>;
